---

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: master
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: master
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
